/* This file was generated by SableCC (http://www.sablecc.org/). */

package dotparse.analysis;

import dotparse.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseADigraphRoot(ADigraphRoot node);
    void caseALinesLine(ALinesLine node);
    void caseAArrowLine(AArrowLine node);
    void caseATextLine(ATextLine node);
    void caseANodeLine(ANodeLine node);
    void caseAEmptyLine(AEmptyLine node);
    void caseAIdsText(AIdsText node);
    void caseAListText(AListText node);
    void caseAElementList(AElementList node);
    void caseAEleElements(AEleElements node);
    void caseACommaElements(ACommaElements node);
    void caseAAssignmentEle(AAssignmentEle node);
    void caseAStringEle(AStringEle node);
    void caseANumberEle(ANumberEle node);

    void caseTDigraph(TDigraph node);
    void caseTNode(TNode node);
    void caseTLbrace(TLbrace node);
    void caseTRbrace(TRbrace node);
    void caseTLbracket(TLbracket node);
    void caseTRbracket(TRbracket node);
    void caseTId(TId node);
    void caseTAssignment(TAssignment node);
    void caseTComma(TComma node);
    void caseTSemicoln(TSemicoln node);
    void caseTArrow(TArrow node);
    void caseTNumber(TNumber node);
    void caseTString(TString node);
    void caseTWhitespace(TWhitespace node);
    void caseTEol(TEol node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
