/* This file was generated by SableCC (http://www.sablecc.org/). */

package dotparse.node;

import dotparse.analysis.*;

@SuppressWarnings("nls")
public final class ACommaElements extends PElements
{
    private PEle _ele_;
    private TComma _comma_;
    private PElements _elements_;

    public ACommaElements()
    {
        // Constructor
    }

    public ACommaElements(
        @SuppressWarnings("hiding") PEle _ele_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PElements _elements_)
    {
        // Constructor
        setEle(_ele_);

        setComma(_comma_);

        setElements(_elements_);

    }

    @Override
    public Object clone()
    {
        return new ACommaElements(
            cloneNode(this._ele_),
            cloneNode(this._comma_),
            cloneNode(this._elements_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaElements(this);
    }

    public PEle getEle()
    {
        return this._ele_;
    }

    public void setEle(PEle node)
    {
        if(this._ele_ != null)
        {
            this._ele_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ele_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PElements getElements()
    {
        return this._elements_;
    }

    public void setElements(PElements node)
    {
        if(this._elements_ != null)
        {
            this._elements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elements_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ele_)
            + toString(this._comma_)
            + toString(this._elements_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ele_ == child)
        {
            this._ele_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._elements_ == child)
        {
            this._elements_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ele_ == oldChild)
        {
            setEle((PEle) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._elements_ == oldChild)
        {
            setElements((PElements) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
