/* This file was generated by SableCC (http://www.sablecc.org/). */

package dotparse.node;

import dotparse.analysis.*;

@SuppressWarnings("nls")
public final class ANodeLine extends PLine
{
    private TNode _node_;
    private PText _text_;
    private PLine _line_;

    public ANodeLine()
    {
        // Constructor
    }

    public ANodeLine(
        @SuppressWarnings("hiding") TNode _node_,
        @SuppressWarnings("hiding") PText _text_,
        @SuppressWarnings("hiding") PLine _line_)
    {
        // Constructor
        setNode(_node_);

        setText(_text_);

        setLine(_line_);

    }

    @Override
    public Object clone()
    {
        return new ANodeLine(
            cloneNode(this._node_),
            cloneNode(this._text_),
            cloneNode(this._line_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANodeLine(this);
    }

    public TNode getNode()
    {
        return this._node_;
    }

    public void setNode(TNode node)
    {
        if(this._node_ != null)
        {
            this._node_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._node_ = node;
    }

    public PText getText()
    {
        return this._text_;
    }

    public void setText(PText node)
    {
        if(this._text_ != null)
        {
            this._text_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._text_ = node;
    }

    public PLine getLine()
    {
        return this._line_;
    }

    public void setLine(PLine node)
    {
        if(this._line_ != null)
        {
            this._line_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._line_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._node_)
            + toString(this._text_)
            + toString(this._line_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._node_ == child)
        {
            this._node_ = null;
            return;
        }

        if(this._text_ == child)
        {
            this._text_ = null;
            return;
        }

        if(this._line_ == child)
        {
            this._line_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._node_ == oldChild)
        {
            setNode((TNode) newChild);
            return;
        }

        if(this._text_ == oldChild)
        {
            setText((PText) newChild);
            return;
        }

        if(this._line_ == oldChild)
        {
            setLine((PLine) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
