/* This file was generated by SableCC (http://www.sablecc.org/). */

package dotparse.node;

import dotparse.analysis.*;

@SuppressWarnings("nls")
public final class ATextLine extends PLine
{
    private TId _id_;
    private PText _text_;
    private PLine _line_;

    public ATextLine()
    {
        // Constructor
    }

    public ATextLine(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PText _text_,
        @SuppressWarnings("hiding") PLine _line_)
    {
        // Constructor
        setId(_id_);

        setText(_text_);

        setLine(_line_);

    }

    @Override
    public Object clone()
    {
        return new ATextLine(
            cloneNode(this._id_),
            cloneNode(this._text_),
            cloneNode(this._line_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATextLine(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PText getText()
    {
        return this._text_;
    }

    public void setText(PText node)
    {
        if(this._text_ != null)
        {
            this._text_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._text_ = node;
    }

    public PLine getLine()
    {
        return this._line_;
    }

    public void setLine(PLine node)
    {
        if(this._line_ != null)
        {
            this._line_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._line_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._text_)
            + toString(this._line_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._text_ == child)
        {
            this._text_ = null;
            return;
        }

        if(this._line_ == child)
        {
            this._line_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._text_ == oldChild)
        {
            setText((PText) newChild);
            return;
        }

        if(this._line_ == oldChild)
        {
            setLine((PLine) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
